PREFIX se: <http://www.w3.org/2002/07/owl#>
PREFIX sx: <http://lod.taxonconcept.org/ontology/txn.owl#>
PREFIX my: <http://myschema.cz/animals#>
PREFIX schema: <http://schema.org/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

CONSTRUCT { ?animal1 schema:type ?charUrl .
  
      ?charUrl a my:OrganismClassification  ;
                sx:class ?classC ;
  				sx:kingdom ?kingdomC ;
    			sx:order ?orderC ;
	      		sx:group ?groupC ;
	      		sx:genus ?genusC ;
    			sx:familu ?familyC ;
    			sx:phylum ?phylumC .
}
FROM <http://localhost:3030/animals-server/data/praha>
FROM <http://localhost:3030/animals-server/data/animals>
WHERE { 
    ?animal2 se:sameAs ?animal1 .
  	?animal2 a sx:Animal .
    ?animal2 schema:type ?type .
    ?type sx:class ?classC ;
	      sx:kingdom ?kingdomC ;
  		  sx:order ?orderC ;
	      sx:group ?groupC ;
	      sx:genus ?genusC ;
  		  sx:familu ?familyC .
      OPTIONAL {?type sx:phylum ?phylumC . }

  	?animal1 my:forView ?forView .
    
  BIND(IRI(CONCAT(str(?animal1), "/charackteristic")) AS ?charUrl)
}


