PREFIX schema: <http://schema.org/>
PREFIX my: <http://myschema.cz/animals#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX sx: <http://lod.taxonconcept.org/ontology/txn.owl#>

CONSTRUCT {
    ?animalURI a sx:Animal ;
	schema:name ?name ,
	       ?nameEng ;
        schema:type ?class ;
	schema:priceSpecification ?price;
	my:forView ?viewable .

    my:forView rdfs:subClassOf rdfs:comment  .

    ?price a schema:priceSpecification ;
	schema:price ?e ; 
	schema:priceCurrency 'CZK' .
}
WHERE {
  BIND(IRI(CONCAT("http://jakubvejr.org/praha/id/",?a)) as ?animalURI)
  BIND(IRI(CONCAT(CONCAT("http://jakubvejr.org/praha/id/",?a),"/price")) as ?price)
  BIND(IRI(CONCAT("http://jakubvejr.org/praha/class/",?d)) as ?class)
  BIND (STRLANG(?b, "cs") AS ?name)
  BIND (STRLANG(?c, "en") AS ?nameEng)
  BIND (STRLANG(IF(?f = "1", "For view", "Not for view"), "en") AS ?viewable)
}

OFFSET 1
