PREFIX s: <http://schema.org/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

CONSTRUCT {
    ?nameLink s:name ?name ;
	s:name ?nameLatin ;
	s:otherName ?otherNames ;
	s:commonNames ?commonNames ;
	s:prey ?prey ;
	s:location ?location ;
	s:skin ?skin ;
	s:kingdom ?kingdom ;
	s:order ?order ;
	s:group ?group ;
	s:genus ?genus ;
	s:family ?family ;
	s:numberSpecies ?numberSpecies ;
	s:phylum ?phylum ;
	s:habitat ?habitat ;
	s:diet ?diet ;
	s:class ?class ;
	s:lifestyle ?lifestyle ;
	s:color ?color ;
	s:predators ?predators ;
	s:status ?status .
}
WHERE {
  BIND (xsd:integer(?a) AS ?numberSpecies)
  BIND (STRLANG(?b, "en") AS ?group)
  BIND (STRLANG(?c, "la") AS ?genus)
  BIND(IRI(CONCAT("http://example.com/animal/",ENCODE_FOR_URI(lcase(REPLACE(?l, " ", "_"))))) as ?nameLink)
  BIND (STRLANG(?e, "en") AS ?name)
  BIND (STRLANG(?k, "la") AS ?nameLatin)
  BIND (STRLANG(?e, "en") AS ?prey)
  BIND (STRLANG(?f, "en") AS ?location)
  BIND (STRLANG(?g, "en") AS ?skin)
  BIND (STRLANG(?i, "en") AS ?kingdom)
  BIND (STRLANG(?m, "en") AS ?diet)
  BIND (STRLANG(?r, "en") AS ?otherNames)
  BIND (STRLANG(?s, "en") AS ?class)
  BIND (STRLANG(?t, "en") AS ?lifestyle)
  BIND (STRLANG(?v, "en") AS ?color)
  BIND (STRLANG(?y, "en") AS ?predators)
  BIND (STRLANG(?aa, "en") AS ?commonNames)
  BIND (STRLANG(?ab, "en") AS ?order)
  BIND (STRLANG(?ad, "en") AS ?family)
  BIND (STRLANG(?ae, "en") AS ?habitat)
  BIND (STRLANG(?af, "en") AS ?status)
  BIND (STRLANG(?al, "en") AS ?phylum)
}

OFFSET 1
LIMIT 3
